In [1]:
import pandas as pd
booksdf = pd.read_csv("allbacks.csv")

In [2]:
booksdf.shape

(15, 5)

In [3]:
booksdf.head()

   rownames  volume  area  weight cover
0         1     885   382     800    hb
1         2    1016   468     950    hb
2         3    1125   387    1050    hb
3         4     239   371     350    hb
4         5     701   371     750    hb

In [4]:
booksdf.info()

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   rownames  15 non-null     int64
 1   volume    15 non-null     int64
 2   area      15 non-null     int64
 3   weight    15 non-null     int64
 4   cover     15 non-null     str
dtypes: int64(4), str(1)
memory usage: 732.0 bytes

In [5]:
round(booksdf.describe(),3)

       rownames    volume     area    weight
count    15.000    15.000   15.000    15.000
mean      8.000   845.267  182.800   706.667
std       4.472   339.880  203.587   268.838
min       1.000   239.000    0.000   250.000
25%       4.500   618.000    0.000   512.500
50%       8.000   929.000    0.000   725.000
75%      11.500  1025.000  376.500   950.000
max      15.000  1492.000  468.000  1075.000

Based on the values for each quartile, the "weight" column is likely to be distributed evenly, overall.

In [6]:
print(booksdf["weight"].mean())
print(booksdf["weight"].median())
print(booksdf["weight"].std())

706.6666666666666
725.0
268.83788706915834

The mean "weight" of the dataset is slightly below the median. This likely indicates that there are a few rows with an especially low "weight" value. The standard deviation is approximately a third of the median, so the average distance of each data point from the mean is not huge.

In [7]:
booksdf.groupby(["cover"]).mean()

       rownames      volume        area      weight
cover
hb          4.0  833.571429  391.714286  796.428571
pb         11.5  855.500000    0.000000  628.125000

When we separate the "weight" values by "cover" type, we see that the mean is quite different between the two groups. The "hb" group's mean "weight" is higher by almost 180--close to two-thirds of the standard deviation of "weight" for the whole dataset. This explains the earlier mean being a bit lower than the median: The "pb" rows have much lower "weight", and there may be more "pb" rows than "hb" rows.

In [8]:
booksdf.sort_values(by=["cover"])

    rownames  volume  area  weight cover
0          1     885   382     800    hb
1          2    1016   468     950    hb
2          3    1125   387    1050    hb
3          4     239   371     350    hb
4          5     701   371     750    hb
5          6     641   367     600    hb
6          7    1228   396    1075    hb
7          8     412     0     250    pb
8          9     953     0     700    pb
9         10     929     0     650    pb
10        11    1492     0     975    pb
11        12     419     0     350    pb
12        13    1010     0     950    pb
13        14     595     0     425    pb
14        15    1034     0     725    pb

We see here that there are 7 "hb" rows and 8 "pb" rows. There is indeed one more "pb" row" than "hb", which brings down the mean "weight" for the dataset.</p>
Additionally, the median "cover" value is "pb", as that is the middle value in the above list that is ordered by "cover".

I consulted the pandas User Guide for this lab:</p>

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html<br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

Github Repo Url: https://github.com/journeyrahman/cs82a-portfolio